"""Agentic music recommender with observable multi-step reasoning.

The MusicAgent orchestrates four steps:
  1. PLAN   — LLM extracts a UserProfile from the natural-language query
  2. RETRIEVE — RAG retriever fetches relevant song context
  3. ACT    — Rule-based recommender scores and ranks songs
  4. CRITIQUE — LLM evaluates recommendations, produces explanation + confidence
"""

import json
from dataclasses import dataclass, field
from typing import List, Optional

from llm_client import LMStudioClient
from recommender import load_songs
from rag_retriever import retrieve_context, build_prompt_context, get_taxonomy_context
from evaluator import evaluate_diversity, evaluate_score_spread, compute_confidence, needs_disclaimer
from few_shot import build_few_shot_prompt, build_baseline_prompt
from logger import get_logger

logger = get_logger("music_agent")


@dataclass
class AgentResult:
    """Container for the complete agent output."""
    recommendations: List[tuple]  # (song_dict, score, explanation)
    explanations: str             # LLM-generated natural-language critique
    confidence: dict              # {"overall", "llm_rating", "diversity", "spread"}
    reasoning_trace: List[str] = field(default_factory=list)


PLAN_PROMPT = """You will receive a user's music preference query. Extract a JSON taste profile with these exact keys:
{
  "favorite_genre": "<genre string>",
  "favorite_mood": "<mood string>",
  "target_energy": <float 0-1>,
  "target_tempo": <int bpm>,
  "target_valence": <float 0-1>,
  "target_danceability": <float 0-1>,
  "likes_acoustic": <bool>,
  "target_acousticness": <float 0-1>
}

Return ONLY the JSON object, nothing else. Use your best judgment for values not mentioned explicitly."""


CRITIQUE_PROMPT_TEMPLATE = """You are evaluating music recommendations generated by a scoring engine.

User query: {query}
Taste profile used: {profile}

Top recommendations (from scoring engine):
{recommendations}

Song catalog context (retrieved via RAG):
{rag_context}

Genre/mood taxonomy for reference:
{taxonomy}

Task: Evaluate these recommendations. Are they cohesive? Do they match the user's stated preferences?
Are there genre biases or blind spots? Then give a concise explanation and confidence score.

Output format — exactly two lines:
Explanation: <one or two sentences>
Confidence: <number between 0 and 1, e.g. 0.85>"""


class MusicAgent:
    """Four-step agentic music recommender."""

    def __init__(self, songs_path: str = "data/songs.csv",
                 llm_client: Optional[LMStudioClient] = None,
                 use_few_shot: bool = True,
                 use_rag: bool = True):
        self.songs = load_songs(songs_path)
        self.llm = llm_client or LMStudioClient()
        self.use_few_shot = use_few_shot
        self.use_rag = use_rag

    def run(self, query: str, k: int = 5) -> AgentResult:
        """Execute the full agent loop and return structured results."""
        trace: List[str] = []

        # --- Step 1: PLAN ---
        logger.info("[STEP 1/4] Planning — extracting taste profile from query...")
        profile = self._plan(query, trace)
        if profile is None:
            logger.warning("LLM planning failed; falling back to default profile.")
            profile = self._default_profile()

        # --- Step 2: RETRIEVE ---
        if self.use_rag:
            logger.info("[STEP 2/4] Retrieving song context via RAG...")
            rag_context = retrieve_context(self.songs, query_hint=query)
            trace.append(f"[RETRIEVE] Context: {len(rag_context)} chars of catalog data")
        else:
            logger.info("[STEP 2/4] RAG disabled; skipping retrieval.")
            rag_context = ""
            trace.append("[RETRIEVE] RAG disabled; no context retrieved.")

        # --- Step 3: ACT ---
        logger.info("[STEP 3/4] Scoring songs with recommender engine...")
        from recommender import recommend_songs as func_recommend
        recommendations = func_recommend(profile, self.songs, k=k)
        scores = [s[1] for s in recommendations]
        if scores:
            trace.append(f"[ACT] Top {k} songs scored (range: {min(scores):.1f}-{max(scores):.1f})")
        else:
            trace.append(f"[ACT] No songs found matching criteria.")

        # --- Step 4: CRITIQUE ---
        logger.info("[STEP 4/4] Critiquing recommendations with LLM...")
        rec_context = build_prompt_context(recommendations, self.songs)
        critique = self._critique(query, profile, rec_context, rag_context, trace)

        explanation, llm_rating = critique

        # Compute combined confidence
        diversity = evaluate_diversity([s[0] for s in recommendations])
        spread = evaluate_score_spread(scores)
        confidence = compute_confidence(llm_rating, diversity, spread)

        if needs_disclaimer(confidence):
            explanation += (
                "\n\n[Note: Confidence is low. These recommendations may not match "
                "your taste well — try being more specific about genre or mood.]"
            )

        logger.info(f"Confidence: {confidence['overall']:.2f} "
                     f"(LLM={llm_rating:.2f}, diversity={diversity:.2f}, spread={spread:.2f})")

        return AgentResult(
            recommendations=recommendations,
            explanations=explanation,
            confidence=confidence,
            reasoning_trace=trace,
        )

    # -- internal helpers ---------------------------------------------------

    def _plan(self, query: str, trace: List[str]) -> Optional[dict]:
        """Ask LLM to extract a UserProfile dict from the query."""
        response = self.llm.chat(
            [{"role": "system", "content": PLAN_PROMPT},
             {"role": "user", "content": f"Query: {query}\nReturn the JSON profile."}],
            temperature=0.1,
            max_tokens=512,
        )
        if not response:
            return None

        trace.append(f"[PLAN] LLM output:\n{response}")
        return self._parse_json(response)

    def _critique(self, query: str, profile: dict, rec_context: str,
                  rag_context: str, trace: List[str]) -> tuple[str, float]:
        """Ask LLM to critique recommendations and return (explanation, confidence)."""
        prompt = CRITIQUE_PROMPT_TEMPLATE.format(
            query=query,
            profile=json.dumps(profile, indent=2),
            recommendations=rec_context,
            rag_context=rag_context,  # already limited by retrieve_context(max_chars)
            taxonomy=get_taxonomy_context(),
        )

        if self.use_few_shot:
            system_msg = build_few_shot_prompt(query) + "\n\nNow critique the scored results."
        else:
            system_msg = "You are a music recommendation evaluator."

        response = self.llm.chat(
            [{"role": "system", "content": system_msg},
             {"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=384,
        )
        if not response:
            return "LLM critique unavailable.", 0.5

        trace.append(f"[CRITIQUE] LLM output:\n{response}")
        explanation, confidence = self._parse_critique(response)
        return explanation, confidence

    @staticmethod
    def _parse_json(text: str) -> Optional[dict]:
        """Extract JSON object from LLM text response."""
        start = text.find("{")
        if start == -1:
            return None
        
        # Robust extraction: decode the first valid JSON object starting from '{'
        try:
            import json
            decoder = json.JSONDecoder()
            obj, _ = decoder.raw_decode(text[start:])
            return obj
        except (json.JSONDecodeError, ValueError):
            return None

    @staticmethod
    def _parse_critique(text: str) -> tuple[str, float]:
        """Extract Explanation and Confidence lines from critique output."""
        explanation = "Recommendations evaluated."
        confidence = 0.5
        for line in text.splitlines():
            clean_line = line.strip().lower()
            if "explanation:" in clean_line:
                explanation = line.split(":", 1)[1].strip()
            elif "confidence:" in clean_line:
                try:
                    # Extract the first number found after the colon
                    part = line.split(":", 1)[1].strip()
                    # Remove any trailing markdown/text
                    confidence_str = "".join(c for c in part if c.isdigit() or c == ".")
                    confidence = float(confidence_str)
                except (ValueError, IndexError):
                    pass
        return explanation, min(max(confidence, 0.0), 1.0)

    @staticmethod
    def _default_profile() -> dict:
        """Fallback profile when LLM planning fails."""
        return {
            "favorite_genre": "",
            "favorite_mood": "",
            "target_energy": 0.5,
            "target_tempo": 120,
            "target_valence": 0.5,
            "target_danceability": 0.5,
            "likes_acoustic": False,
            "target_acousticness": 0.5,
        }
